# Generated by Django 5.2.5 on 2025-08-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Solicitud de reparación de baches', max_length=100, verbose_name='Nombre de la Solicitud')),
                ('direccion', models.CharField(help_text='Ej: Dirección de Operaciones', max_length=100, verbose_name='Dirección Responsable')),
                ('descripcion_corta', models.TextField(help_text='Breve descripción del objetivo de esta solicitud.', verbose_name='Descripción Corta')),
            ],
            options={
                'verbose_name': 'Tipo de Solicitud',
                'verbose_name_plural': 'Tipos de Solicitudes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Ingresa tu correo electrónico.', max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(help_text='Formato: +56912345678', max_length=12, verbose_name='Teléfono Celular')),
                ('descripcion', models.TextField(help_text='Detalla tu solicitud aquí.', verbose_name='Descripción de la Solicitud')),
                ('adjunto', models.FileField(blank=True, help_text='Adjunta documentos relevantes (ej. PDF, imágenes).', null=True, upload_to='solicitudes_adjuntos/', verbose_name='Archivo Adjunto')),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Completo (Clave Única)')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT (Clave Única)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelta', 'Resuelta'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50, verbose_name='Estado de la Solicitud')),
                ('tipo_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='solicitudesF.tiposolicitud', verbose_name='Tipo de Solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
